export const KeyboardButtonList = [
    "NULL",
    "CANCEL", // ^break
    "HELP",
    "BACK_SPACE",
    "TAB",
    "CLEAR",
    "RETURN",
    "ENTER",
    "SHIFT",
    "CONTROL",
    "ALT",
    "PAUSE",
    "ESCAPE",
    "SPACE",
    "PAGE_UP",
    "PAGE_DOWN",
    "END",
    "HOME",
    "ARROW_LEFT",
    "LEFT",
    "ARROW_UP",
    "UP",
    "ARROW_RIGHT",
    "RIGHT",
    "ARROW_DOWN",
    "DOWN",
    "INSERT",
    "DELETE",
    "SEMICOLON",
    "EQUALS",

    "NUMPAD0", // number pad keys
    "NUMPAD1",
    "NUMPAD2",
    "NUMPAD3",
    "NUMPAD4",
    "NUMPAD5",
    "NUMPAD6",
    "NUMPAD7",
    "NUMPAD8",
    "NUMPAD9",
    "MULTIPLY",
    "ADD",
    "SEPARATOR",
    "SUBTRACT",
    "DECIMAL",
    "DIVIDE",

    "F1", // function keys
    "F2",
    "F3",
    "F4",
    "F5",
    "F6",
    "F7",
    "F8",
    "F9",
    "F10",
    "F11",
    "F12",

    "COMMAND", // Apple command key
    "META", // alias for Windows key
];

export const IfType = ["Boolean", "Number", "String"];
export const ConditionList = ["==", "!=", ">=", "<=", ">", "<", "Empty", "Not Empty", "Not Matches", "Matches", "Includes", "Not Includes"];

export const ConvertList = ["Date Time", "String", "Number", "Integer", "Float", "Boolean", "HEX", "JSON"];

export const WaitUntil = [
    "Object Located",
    "Object Clickable",
    "Object Not Clickable",
    "Object Enabled",
    "Object Disabled",
    "Object Selected",
    "Object Not Selected",
    "Object Visible",
    "Object Not Visible",
    "Object Staleness Of",
    "Objects Located",
    "Able To Switch Frame",
    "Alert Present",
];

export const RandomType = [
    "Full Name",
    "First Name",
    "Last Name",
    "Middle Name",
    "Username",
    "Prefix",
    "Gender",
    "Street",
    "Address",
    "Email",
    "Bio",
    "Country",
    "State",
    "City",
    "Timezone",
    "Paragraph",
    "Paragraphs",
    "Slug",
    "Sentence",
    "Sentences",
    "Lines",
    "Words",
    "Word",
    "Nanoid",
    "UUID",
    "URL",
    "Avatar",
    "Color",
    "IP Address",
    "MAC Address",
    "IPV4 Address",
    "IPV6 Address",
    "HTTP Method",
    "HTTP Status Code",
    "Protocol",
    "User Agent",
    "Cardinal Direction",
    "Ordinal Direction",
    "Emoji",
    "Mime Type",
    "File Extension",
    "File Name",
    "File Type",
    "Cron",
    "Network Interface",
    "Mongo Object Id",
    "IMEI",
    "Symbol",
    "Zodiac Sign",
    "Designation",
];
