const errorContstants = {
    UNAUTHORIZED: "Unauthorized!",
    ACCOUNT_BLOCKED: "Account Blocked!",
    ACCOUNT_INACTIVE: "Account Inactive!",
    INCORRECT_PASSWORD: "Incorrect Password!",
    INVALID_PERMISSION: "Invalid Permission!",
    ENDPOINT_NOT_FOUND: "Endpoint Not Found!",
    RECORD_NOT_FOUND: "Record Not Found!",
    INVALID_FILE: "Invalid File",
    INVALID_BUCKET: "Invalid Bucket",
    INVALID_FOLDER: "Invalid Folder",
    EMAIL_ALREADY_VERIFIED: "Email Already Verified",
    EMAIL_NOT_VERIFIED: "Email Not Verified",
    REFRESH_TOKEN_NOT_FOUND: "Refresh Token Not Found",
    ACCESS_TOKEN_NOT_FOUND: "Access Token Not Found",
    SOMETHING_WENT_WRONG: "Something Went Wrong!",
    TIMEOUT: "Timeout!",
    NOT_AN_ACTIVE_SESSION: "Not An Active Session!",
    UNABLE_TO_DELETE_MASTER_DATABASE: "Unable To Delete Master Database!",
    UNAUTHORIZED_ORIGIN: "Unauthorized Origin",
    CUSTOMER_DATABASE_ALREADY_EXIST: "Customer Database Already Exists",
};
export default errorContstants;
